version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: "239334275706"
    ECR_REPO: blacklist-service
    CONTAINER_NAME: blacklist-service

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias para pruebas..."
      - pip install --upgrade pip
      - pip install -r blacklist-service/requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - cd blacklist-service && pytest -q && cd ..
      - echo "Login a Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - export REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:-latest}
      - export IMAGE_URI=$REPO_URI:$IMAGE_TAG

  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build -t $IMAGE_URI ./blacklist-service
      - docker tag $IMAGE_URI $REPO_URI:latest

  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push $IMAGE_URI
      - docker push $REPO_URI:latest
      - echo "Generando artefacto de imagen para uso posterior..."
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json
      - cat imageDetail.json
      - cat taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json